import ccxt

exchanges = {
"binance" : ccxt.binance(), 
"wazirx": ccxt.wazirx(),
"bibox": ccxt.bibox(),
"bigone": ccxt.bigone(),
"binance": ccxt.binance(),
"binancecoinm": ccxt.binancecoinm(),
"binanceus": ccxt.binanceus(),
"binanceusdm": ccxt.binanceusdm(),
}
exchanges_ = {
# "binance" : ccxt.binance(), 
# "wazirx": ccxt.wazirx()


"aax": ccxt.aax(),
"ascendex": ccxt.ascendex(),
# "bequant": ccxt.bequant(),
"bibox": ccxt.bibox(),
"bigone": ccxt.bigone(),
"binance": ccxt.binance(),
"binancecoinm": ccxt.binancecoinm(),
"binanceus": ccxt.binanceus(),
"binanceusdm": ccxt.binanceusdm(),
# "bitbay": ccxt.bitbay(),
"bitbns": ccxt.bitbns(),
"bitcoincom": ccxt.bitcoincom(),
"bitfinex": ccxt.bitfinex(),
"bitfinex2": ccxt.bitfinex2(),
"bitget": ccxt.bitget(),
"bithumb": ccxt.bithumb(),
"bitmart": ccxt.bitmart(),
"bitmex": ccxt.bitmex(),
"bitopro": ccxt.bitopro(),
"bitpanda": ccxt.bitpanda(),
"bitrue": ccxt.bitrue(),
"bittrex": ccxt.bittrex(),
"bitvavo": ccxt.bitvavo(),
"bkex": ccxt.bkex(),
"blockchaincom": ccxt.blockchaincom(),
"btcturk": ccxt.btcturk(),
"bw": ccxt.bw()

# 'bybit': ccxt.bybit(),
# 'bytetrade': ccxt.bytetrade(),
# 'cdax': ccxt.cdax(),
# 'cex': ccxt.cex(),
# 'coinbase': ccxt.coinbase(),
# 'coinbaseprime': ccxt.coinbaseprime(),
# 'coinbasepro': ccxt.coinbasepro(),
# 'coinex': ccxt.coinex(),
# 'coinfalcon': ccxt.coinfalcon(),
# 'coinflex': ccxt.coinflex(),
# 'coinone': ccxt.coinone(),
# 'crex24': ccxt.crex24(),
# 'cryptocom': ccxt.cryptocom(),
# 'currencycom': ccxt.currencycom(),
# 'delta': ccxt.delta(),
# 'deribit': ccxt.deribit(),
# 'digifinex': ccxt.digifinex(),
# 'exmo': ccxt.exmo(),
# 'fmfwio': ccxt.fmfwio(),
# 'ftx': ccxt.ftx(),
# 'ftxus': ccxt.ftxus(),
# 'gate': ccxt.gate(),
# 'gateio': ccxt.gateio(),
# 'gemini': ccxt.gemini(),
# 'hitbtc': ccxt.hitbtc(),
# 'hitbtc3': ccxt.hitbtc3(),
# 'hollaex': ccxt.hollaex(),
# 'huobi': ccxt.huobi(),
# 'huobijp': ccxt.huobijp(),
# 'huobipro': ccxt.huobipro(),
# 'idex': ccxt.idex(),
# 'kucoin': ccxt.kucoin(),
# 'kuna': ccxt.kuna(),
# 'latoken': ccxt.latoken(),
# 'lbank': ccxt.lbank(),
# 'lbank2': ccxt.lbank2(),
# 'liquid': ccxt.liquid(),
# 'luno': ccxt.luno(),
# 'lykke': ccxt.lykke(),
# 'mexc': ccxt.mexc(),
# 'mexc3': ccxt.mexc3(),
# 'novadax': ccxt.novadax(),
# 'oceanex': ccxt.oceanex(),
# 'okcoin': ccxt.okcoin(),
# 'okex': ccxt.okex(),
# 'okex5': ccxt.okex5(),
# 'okx': ccxt.okx(),
# 'phemex': ccxt.phemex(),
# 'poloniex': ccxt.poloniex(),
# 'probit': ccxt.probit(),
# 'qtrade': ccxt.qtrade(),
# 'stex': ccxt.stex(),
# 'timex': ccxt.timex(),
# 'upbit': ccxt.upbit(),
# 'wazirx': ccxt.wazirx(),
# 'whitebit': ccxt.whitebit(),
# 'zb': ccxt.zb(),
# 'zonda': ccxt.zonda(),
}
